title: Hardin Valley Ward
description: of The Church of Jesus Christ of Latter-Day Saints
logo: images/hardin-valley-ward-image0.jpeg
show_downloads: false
google_analytics: UA-169258073-1

theme: jekyll-theme-minimal
