title: Hardin Valley Ward
description: News & Information
logo: images/hardin-valley-ward-image1.jpeg
disclaimer: This is not an official website of The Church of Jesus Christ of Latter-day Saints.
contact:
  name: Chris Lunsford
  email: admin@hardinvalleyward.org

google_analytics: UA-169258073-1


theme: jekyll-theme-minimal
show_downloads: false


permalink: /:categories/:year/:month/:day/:title:output_ext
excerpt_separator: <!--more-->
